language: python
python:
  - "2.7.13"
  - "3.6"
# command to install dependencies
install: 
  - pip install -r requirements.txt --upgrade --ignore-installed six
  - pip install -r test-requirements.txt
  - pip install pycodestyle
# command to run tests
script: pycodestyle samples/*
